name: tinder_cards
description: A new Flutter project.

version: 2.0.7+117

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  simple_animations: 1.3.3
  firebase_auth: ^0.15.3+1
  firebase_core: ^0.4.3+2
  flutter_icons: ^1.1.0
  flip_card: ^0.5.0
  flutter_sticky_header:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - res/

  fonts:
    - family: Quicksand
      fonts:
        - asset: res/fonts/Quicksand-Regular.ttf
        - asset: res/fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: res/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: res/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: res/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: res/fonts/Montserrat-Regular.ttf
        - asset: res/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: res/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: res/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: res/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: res/fonts/PoppinsRegular.ttf
        - asset: res/fonts/PoppinsMedium.ttf
          weight: 400
        - asset: res/fonts/PoppinsLight.ttf
          weight: 200
        - asset: res/fonts/PoppinsSemiBold.ttf
          weight: 500
        - asset: res/fonts/PoppinsBold.ttf
          weight: 700
    - family: Playfair
      fonts:
        - asset: res/fonts/PlayfairDisplaySC-Regular.ttf
        - asset: res/fonts/PlayfairDisplaySC-Regular.ttf
          weight: 400
        - asset: res/fonts/PlayfairDisplaySC-Regular.ttf
          weight: 200
        - asset: res/fonts/PlayfairDisplaySC-Bold.ttf
          weight: 500
        - asset: res/fonts/PlayfairDisplaySC-Black.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
